---

# Action Config
actions:
  addons:
    #  action: src.jbi.whiteboard_actions.default
    contact: tbd
    description: Addons whiteboard tag for AMO Team
    # enabled: false
    parameters:
      jira_project_key: WEBEXT
      whiteboard_tag: addons
  fidedi:
    contact: tbd
    description: Firefox Desktop Integration whiteboard tag
    parameters:
      jira_project_key: FIDEDI
      whiteboard_tag: fidedi
  fidefe:
    contact: tbd
    description: Firefox Front End whiteboard tag
    parameters:
      jira_project_key: FIDEFE
      whiteboard_tag: fidefe
  fxatps:
    contact: tbd
    description: Privacy & Security and Anti-Tracking Team whiteboard tag
    parameters:
      jira_project_key: FXATPS
      whiteboard_tag: fxatps
  fxsync:
    contact: tbd
    description: Firefox Sync Team whiteboard tag
    parameters:
      jira_project_key: SYNC
      whiteboard_tag: fxsync
  gv:
    contact: tbd
    description: GeckoView Team whiteboard tag
    parameters:
      jira_project_key: ANDP
      whiteboard_tag: gv
  mr2qa:
    contact: tbd
    description: MR2 whiteboard tag
    parameters:
      jira_project_key: MR2
      whiteboard_tag: mr2qa
  mv3:
    contact: tbd
    description: MV3 whiteboard tag
    parameters:
      jira_project_key: WEBEXT
      whiteboard_tag: mv3
  prodtest:
    contact: tbd
    description: ProdTest tag
    enabled: true
    parameters:
      jira_project_key: OSS
      whiteboard_tag: prodtest
  proton:
    contact: tbd
    description: Proton whiteboard tag for Firefox Frontend
    parameters:
      jira_project_key: FIDEFE
      whiteboard_tag: proton
  relops:
    contact: tbd
    description: Release Operations Team Tag
    parameters:
      jira_project_key: RELOPS
      whiteboard_tag: relops
  snt:
    contact: tbd
    description: Search/NewTab Team Tag
    parameters:
      jira_project_key: SNT
      whiteboard_tag: snt
